"""python -m db.cli init | status | export-schema"""
import sys
from pathlib import Path
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable
from .models import metadata
from .store import get_engine, init_schema, table_counts

SCHEMA_PATH = Path(__file__).with_name("schema.sql")


def export_schema() -> str:
    ddl = [str(CreateTable(t, if_not_exists=True).compile(dialect=postgresql.dialect())).strip() + ";"
           for t in metadata.sorted_tables]
    for t in metadata.sorted_tables:
        ddl += [str(CreateIndex(i, if_not_exists=True).compile(dialect=postgresql.dialect())).strip() + ";" for i in t.indexes]
    rls = [f"ALTER TABLE public.{t.name} ENABLE ROW LEVEL SECURITY;" for t in metadata.sorted_tables]
    return ("-- Generated by `python -m db.cli export-schema` from db/models.py. Paste into the Supabase SQL editor.\n\n"
            + "\n\n".join(ddl)
            + "\n\n-- Lock the tables from Supabase's public REST API (anon key). Our server connects with the\n"
              "-- database role via DATABASE_URL, not through the REST API.\n" + "\n".join(rls) + "\n")


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "status"
    if cmd == "export-schema":
        SCHEMA_PATH.write_text(export_schema()); print(f"wrote {SCHEMA_PATH}")
    elif cmd in ("init", "status"):
        eng = get_engine()
        print("dialect:", eng.dialect.name, "| host:", eng.url.host or "(local file)")
        if cmd == "init":
            init_schema(eng); print("schema ready")
        counts = table_counts(eng)
        print("rows per table:", counts)
        if any(v is None for v in counts.values()):
            print("-> some tables are missing: run `python -m db.cli init`")
    else:
        print(__doc__)


if __name__ == "__main__":
    main()
