-- Generated by `python -m db.cli export-schema` from db/models.py. Paste into the Supabase SQL editor.

CREATE TABLE IF NOT EXISTS insights (
	run_id VARCHAR NOT NULL, 
	insight_id VARCHAR NOT NULL, 
	product_id VARCHAR, 
	product_name VARCHAR, 
	segment JSONB, 
	orders INTEGER, 
	returns_count INTEGER, 
	return_rate FLOAT, 
	lift FLOAT, 
	evidence JSONB, 
	recommendation JSONB, 
	status VARCHAR, 
	attempts INTEGER, 
	open_issues JSONB, 
	review_status VARCHAR DEFAULT 'pending' NOT NULL, 
	reviewer VARCHAR, 
	review_note TEXT, 
	reviewed_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (run_id, insight_id)
);

CREATE TABLE IF NOT EXISTS llm_cache (
	key VARCHAR NOT NULL, 
	value TEXT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS returns (
	return_id VARCHAR NOT NULL, 
	order_id VARCHAR, 
	product_id VARCHAR, 
	product_name VARCHAR, 
	category VARCHAR, 
	size VARCHAR, 
	colour VARCHAR, 
	return_reason VARCHAR, 
	return_comment TEXT, 
	return_date DATE, 
	primary_reason VARCHAR, 
	sub_reason VARCHAR, 
	body_area VARCHAR, 
	classification_source VARCHAR, 
	confidence FLOAT, 
	run_id VARCHAR, 
	PRIMARY KEY (return_id)
);

CREATE TABLE IF NOT EXISTS runs (
	run_id VARCHAR NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	fast_model VARCHAR, 
	strong_model VARCHAR, 
	est_usd FLOAT, 
	llm_calls INTEGER, 
	report JSONB, 
	PRIMARY KEY (run_id)
);

CREATE INDEX IF NOT EXISTS ix_insights_review ON insights (review_status);

CREATE INDEX IF NOT EXISTS ix_returns_product_id ON returns (product_id);

-- Lock the tables from Supabase's public REST API (anon key). Our server connects with the
-- database role via DATABASE_URL, not through the REST API.
ALTER TABLE public.insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.llm_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.runs ENABLE ROW LEVEL SECURITY;
